logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug

spring:
  datasource:
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${DB_URL:jdbc:localhost:3306/local_db}
    username: ${DB_USERNAME:username}
    password: ${DB_PASSWORD:password}
  batch:
    job:
      name: simple

batch:
  query:
    best-review: ${BEST_REVIEW_QUERY:SELECT * FROM review WHERE rating > 4}
